# Bibliography  

“Breastfeeding Benefits Both Baby and Mom  | DNPAO | CDC.” Centers for Disease Control and Prevention, 7 Sept. 2023, https://www.cdc.gov/nccdphp/dnpao/features/breastfeeding-benefits/index.html.  

“Breastfeeding FAQs: How Much and How Often (for Parents) - Nemours KidsHealth.” Nemours KidsHealth - the Web’s Most Visited Site about Children’s Health, https://kidshealth.org/en/parents/breastfeed-often.html. Accessed 7 Dec. 2023.  

“Frequently Asked Questions (FAQs)  | Breastfeeding | CDC.” Centers for Disease Control and Prevention, 18 Apr. 2023, https://www.cdc.gov/breastfeeding/faq/index.htm.  

“Kaplan Meier Curve • Simply Explained - DATAtab.” Online Statistics Calculator: Hypothesis Testing, t-Test, Chi-Square, Regression, Correlation, Analysis of Variance, Cluster Analysis, https://datatab.net/tutorial/kaplan-meier-curve. Accessed 4 Dec. 2023.

Wasie Kasahun, Abebaw, et al. “Predictors of Exclusive Breastfeeding Duration among 6–12 Month Aged Children in Gurage Zone, South Ethiopia: A Survival Analysis | International Breastfeeding Journal | Full Text.” BioMed Central, 21 Apr. 2017, https://internationalbreastfeedingjournal.biomedcentral.com/articles/10.1186/s13006-017-0107-z.

\pagebreak
# Appendix  

