# Conclusion  

As shown by the multiple single-variate models, the mother's race, smoking status, and years of education played a role in determining whether or not they weaned their child. While performing the analysis, the correlation between poverty status and the race of the mother had to be considered. Because the data is from the 70s, it makes sense, intuitively, that race is associated with poverty status. Therefore, the poverty status appears to be significant when considered in a model with race but rather insignificant otherwise. Additionally, smoking status was also slightly correlated with race but not to the same extent. To take these relationships into account, the conclusions regarding the associations between smoking status and race with breastfeeding duration were drawn from hazard ratios from separate models. This was so we could have the most accurate final results. `yschool` was rather significant in the "full" model but it was also important to consider it within the context of the mother's age. The age of the mother and her years of education have a non-randomly correlated relationship. A person cannot have more years of education than she is old. However, in the context of this analysis, the age of the mother didn't appear to be a significant influence on breastfeeding duration on its own or in tandem with the years of education. Generally, it can be concluded that smoking mothers tend to wean their children faster than non-smoking mothers and that non-white mothers had a tendency to wean sooner than white mothers.  

## Discussion  

There are a few possible explanations for the results. First of all, in regards to the trends with the smokers versus non-smokers, previous research has shown that smoking mothers' breast milk tends to dry up sooner than smoking mothers. This can can essentially force them too wean their child after a certain point as they can no longer provide any breast milk (“Tobacco and E-Cigarettes | Breastfeeding | CDC”). As our findings follow similar trends, with smoking mothers weaning sooner, this is a viable explanation for the findings. In the case of the mother's race being significant, perhaps it is a combination of things such as socioeconomic status, occupation, and other lifestyle factors that make a difference. As mentioned before, in the 1970s, socioeconomic status was still tied to one's race. However, generally, poverty status was associated with weaning later than those not in poverty. This could be explained by the fact that solid foods are more expensive than breastfeeding, which is free so long as the mother can produce breast milk. One additional hypothesis is that mothers with certain occupations may be more likely to wean early due to the nature of their occupations. For example, it may be more difficult for women who work in offices to bring their child to work and breastfeed them. However, we do not have any data on the occupation of these women so none of these hypotheses can be proven. Thus, while there are general trends being observed, there isn't enough data to make strong conclusions about the causes of the trends. Cox models can only show associations in these cases, so more powerful statistical methods may be required.  

On the topic of the potential outliers identified during the sensitivity analysis, there are a few reasons for why they have been pointed out as such. First of all, inputs such as the duration of 195 weeks for observation 18 could be input errors. If they aren't errors, then these observations could simply be the result of natural variations arising from unobserved or immeasurable differences between all of the mothers in the study. It is completely possible, though arguably a bit unusual, for women to breastfeed for prolonged periods of time. There have been instances of women breastfeeding for more than 5 years, so this might just be an observation of this somewhat rare instance.  

Additional research on this topic is not a waste of effort either. Because breastfeeding is largely beneficial for infants and their development, further research into the the main limitations mothers face when deciding how long to breastfeed their children could be beneficial. Stronger causal associations could help lawmakers and such adjust or create legislation that helps give mothers the accommodations they need to be able to raise a healthy generation of children.  