## Please follow this example  


# For Tables  
```{r}
df <- data.frame(a = c(1:3), b = c(4:6))

#make table 
## for the caption, make sure to have that \\label{tab:NAME} format
## Use the the kableExtra and kable_styling options as shown below 
df  %>% 
  kableExtra::kable(caption = "\\label{tab:tdepsumry}Coefficients for Final Time-Dependent Model",
                    align = 'c',
                    booktabs = T) %>% 
  kable_styling(latex_options = c("striped", "HOLD_position"), 
                    full_width = F, font_size = 10
                    )
```

if you do this properly, you can just do Table \@ref(tab:tdepsumry) and it'll get the number automatically and it'll hyperlink to the table too.  

# For Plots  
```{r randomsectname, fig.align='center', fig.height=3.5, message=FALSE, warning=FALSE, fig.cap="Density Plots for Sepal.Length"}

ggplot(iris, aes(x = Sepal.Length)) + 
  geom_density(aes(color = Species, fill = Species), alpha = 0.3) + 
  xlab("Sepal Length") + 
  labs(color = "Species") +
  guides(fill = "none", 
         color = guide_legend(title.hjust = -.5)) + 
  theme(legend.position = c(.95,.95),
        legend.justification = c("right", "top"), 
        legend.box.just = "right",
        legend.key.size = unit(.30, 'cm'), 
        panel.border = element_blank(),
    axis.line = element_line(color = "black")) 


```

You can do something similar for the plots too. Just make sure to name the section (section names have to be unique) and a caption and then you can do Fig.\@ref(fig:randomsectname).  
